#!/bin/sh

set -e

COMMAND=$1
shift || true

case $COMMAND in
  generate-test-proto)
    go run github.com/hanpama/protograph/cmd/protograph compile-proto -root tests/simple/graphql -rootpkg simple -out tests/simple/proto
    # Generate Go messages and gRPC service code
    protoc -I tests/simple/proto/simple \
      --go_out=tests/simple/server/grpcproto --go_opt=paths=source_relative,Muser.proto=grpcproto/,Mschema.proto=grpcproto/ \
      --go-grpc_out=tests/simple/server/grpcproto --go-grpc_opt=paths=source_relative,Muser.proto=grpcproto/,Mschema.proto=grpcproto/ \
      user.proto schema.proto
    ;;
  simple-grpc-server)
    go run tests/simple/server/main.go -addr ':50051'
    ;;
  simple-graphql-server)
    go run github.com/hanpama/protograph/cmd/protograph serve -graphql.root tests/simple/graphql -graphql.rootpkg simple -transport.backend '*=localhost:50051' -server.addr ':8081'
    ;;
  *)
    echo "Invalid command '$COMMAND'" >&2
    exit 1
    ;;
esac
