// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: user.proto

package grpcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Typename      string                 `protobuf:"bytes,1,opt,name=typename,proto3" json:"typename,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSource) Reset() {
	*x = NodeSource{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSource) ProtoMessage() {}

func (x *NodeSource) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSource.ProtoReflect.Descriptor instead.
func (*NodeSource) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *NodeSource) GetTypename() string {
	if x != nil {
		return x.Typename
	}
	return ""
}

func (x *NodeSource) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SearchResultSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*SearchResultSource_Post
	//	*SearchResultSource_User
	//	*SearchResultSource_Organization
	Value         isSearchResultSource_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResultSource) Reset() {
	*x = SearchResultSource{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResultSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResultSource) ProtoMessage() {}

func (x *SearchResultSource) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResultSource.ProtoReflect.Descriptor instead.
func (*SearchResultSource) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResultSource) GetValue() isSearchResultSource_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SearchResultSource) GetPost() *PostSource {
	if x != nil {
		if x, ok := x.Value.(*SearchResultSource_Post); ok {
			return x.Post
		}
	}
	return nil
}

func (x *SearchResultSource) GetUser() *UserSource {
	if x != nil {
		if x, ok := x.Value.(*SearchResultSource_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *SearchResultSource) GetOrganization() *OrganizationSource {
	if x != nil {
		if x, ok := x.Value.(*SearchResultSource_Organization); ok {
			return x.Organization
		}
	}
	return nil
}

type isSearchResultSource_Value interface {
	isSearchResultSource_Value()
}

type SearchResultSource_Post struct {
	Post *PostSource `protobuf:"bytes,23707,opt,name=Post,proto3,oneof"`
}

type SearchResultSource_User struct {
	User *UserSource `protobuf:"bytes,27303,opt,name=User,proto3,oneof"`
}

type SearchResultSource_Organization struct {
	Organization *OrganizationSource `protobuf:"bytes,9145,opt,name=Organization,proto3,oneof"`
}

func (*SearchResultSource_Post) isSearchResultSource_Value() {}

func (*SearchResultSource_User) isSearchResultSource_Value() {}

func (*SearchResultSource_Organization) isSearchResultSource_Value() {}

type UserSource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,23236,opt,name=id,proto3" json:"id,omitempty"`
	Email          string                 `protobuf:"bytes,20000,opt,name=email,proto3" json:"email,omitempty"`
	Name           string                 `protobuf:"bytes,29928,opt,name=name,proto3" json:"name,omitempty"`
	Age            int32                  `protobuf:"varint,17865,opt,name=age,proto3" json:"age,omitempty"`
	IsActive       bool                   `protobuf:"varint,16737,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7338,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,18192,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	OrganizationId string                 `protobuf:"bytes,16616,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserSource) Reset() {
	*x = UserSource{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSource) ProtoMessage() {}

func (x *UserSource) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSource.ProtoReflect.Descriptor instead.
func (*UserSource) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserSource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserSource) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSource) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserSource) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UserSource) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserSource) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UserSource) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type OrganizationSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,23236,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,29928,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,13174,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationSource) Reset() {
	*x = OrganizationSource{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationSource) ProtoMessage() {}

func (x *OrganizationSource) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationSource.ProtoReflect.Descriptor instead.
func (*OrganizationSource) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *OrganizationSource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganizationSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizationSource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PostSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,23236,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,3552,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,24511,opt,name=content,proto3" json:"content,omitempty"`
	Published     bool                   `protobuf:"varint,22952,opt,name=published,proto3" json:"published,omitempty"`
	AuthorId      string                 `protobuf:"bytes,29641,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostSource) Reset() {
	*x = PostSource{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostSource) ProtoMessage() {}

func (x *PostSource) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostSource.ProtoReflect.Descriptor instead.
func (*PostSource) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *PostSource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PostSource) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostSource) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostSource) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

func (x *PostSource) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type CommentSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,23236,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,24511,opt,name=content,proto3" json:"content,omitempty"`
	PostId        string                 `protobuf:"bytes,23806,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,29641,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentSource) Reset() {
	*x = CommentSource{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentSource) ProtoMessage() {}

func (x *CommentSource) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentSource.ProtoReflect.Descriptor instead.
func (*CommentSource) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *CommentSource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommentSource) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentSource) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CommentSource) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type ProfileSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,23236,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,12974,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bio           string                 `protobuf:"bytes,20192,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,20871,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileSource) Reset() {
	*x = ProfileSource{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileSource) ProtoMessage() {}

func (x *ProfileSource) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileSource.ProtoReflect.Descriptor instead.
func (*ProfileSource) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *ProfileSource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfileSource) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfileSource) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *ProfileSource) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type CreateUserInputSource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Email          string                 `protobuf:"bytes,20000,opt,name=email,proto3" json:"email,omitempty"`
	Name           string                 `protobuf:"bytes,29928,opt,name=name,proto3" json:"name,omitempty"`
	Age            int32                  `protobuf:"varint,17865,opt,name=age,proto3" json:"age,omitempty"`
	OrganizationId string                 `protobuf:"bytes,16616,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUserInputSource) Reset() {
	*x = CreateUserInputSource{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserInputSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserInputSource) ProtoMessage() {}

func (x *CreateUserInputSource) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserInputSource.ProtoReflect.Descriptor instead.
func (*CreateUserInputSource) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *CreateUserInputSource) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserInputSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserInputSource) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateUserInputSource) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type UpdateUserInputSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,20000,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,29928,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,17865,opt,name=age,proto3" json:"age,omitempty"`
	IsActive      bool                   `protobuf:"varint,16737,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInputSource) Reset() {
	*x = UpdateUserInputSource{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInputSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInputSource) ProtoMessage() {}

func (x *UpdateUserInputSource) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInputSource.ProtoReflect.Descriptor instead.
func (*UpdateUserInputSource) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserInputSource) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserInputSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserInputSource) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UpdateUserInputSource) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ResolveQueryUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,23236,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveQueryUserRequest) Reset() {
	*x = ResolveQueryUserRequest{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveQueryUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveQueryUserRequest) ProtoMessage() {}

func (x *ResolveQueryUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveQueryUserRequest.ProtoReflect.Descriptor instead.
func (*ResolveQueryUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *ResolveQueryUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResolveQueryUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *UserSource            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveQueryUserResponse) Reset() {
	*x = ResolveQueryUserResponse{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveQueryUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveQueryUserResponse) ProtoMessage() {}

func (x *ResolveQueryUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveQueryUserResponse.ProtoReflect.Descriptor instead.
func (*ResolveQueryUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *ResolveQueryUserResponse) GetData() *UserSource {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResolveQueryUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveQueryUsersRequest) Reset() {
	*x = ResolveQueryUsersRequest{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveQueryUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveQueryUsersRequest) ProtoMessage() {}

func (x *ResolveQueryUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveQueryUsersRequest.ProtoReflect.Descriptor instead.
func (*ResolveQueryUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

type ResolveQueryUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*UserSource          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveQueryUsersResponse) Reset() {
	*x = ResolveQueryUsersResponse{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveQueryUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveQueryUsersResponse) ProtoMessage() {}

func (x *ResolveQueryUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveQueryUsersResponse.ProtoReflect.Descriptor instead.
func (*ResolveQueryUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *ResolveQueryUsersResponse) GetData() []*UserSource {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResolveQueryNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,23236,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveQueryNodeRequest) Reset() {
	*x = ResolveQueryNodeRequest{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveQueryNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveQueryNodeRequest) ProtoMessage() {}

func (x *ResolveQueryNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveQueryNodeRequest.ProtoReflect.Descriptor instead.
func (*ResolveQueryNodeRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *ResolveQueryNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResolveQueryNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *NodeSource            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveQueryNodeResponse) Reset() {
	*x = ResolveQueryNodeResponse{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveQueryNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveQueryNodeResponse) ProtoMessage() {}

func (x *ResolveQueryNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveQueryNodeResponse.ProtoReflect.Descriptor instead.
func (*ResolveQueryNodeResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *ResolveQueryNodeResponse) GetData() *NodeSource {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResolveQuerySearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          string                 `protobuf:"bytes,27110,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveQuerySearchRequest) Reset() {
	*x = ResolveQuerySearchRequest{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveQuerySearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveQuerySearchRequest) ProtoMessage() {}

func (x *ResolveQuerySearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveQuerySearchRequest.ProtoReflect.Descriptor instead.
func (*ResolveQuerySearchRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *ResolveQuerySearchRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

type ResolveQuerySearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*SearchResultSource  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveQuerySearchResponse) Reset() {
	*x = ResolveQuerySearchResponse{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveQuerySearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveQuerySearchResponse) ProtoMessage() {}

func (x *ResolveQuerySearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveQuerySearchResponse.ProtoReflect.Descriptor instead.
func (*ResolveQuerySearchResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *ResolveQuerySearchResponse) GetData() []*SearchResultSource {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResolveMutationCreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *CreateUserInputSource `protobuf:"bytes,23683,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveMutationCreateUserRequest) Reset() {
	*x = ResolveMutationCreateUserRequest{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMutationCreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMutationCreateUserRequest) ProtoMessage() {}

func (x *ResolveMutationCreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMutationCreateUserRequest.ProtoReflect.Descriptor instead.
func (*ResolveMutationCreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *ResolveMutationCreateUserRequest) GetInput() *CreateUserInputSource {
	if x != nil {
		return x.Input
	}
	return nil
}

type ResolveMutationCreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *UserSource            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveMutationCreateUserResponse) Reset() {
	*x = ResolveMutationCreateUserResponse{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMutationCreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMutationCreateUserResponse) ProtoMessage() {}

func (x *ResolveMutationCreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMutationCreateUserResponse.ProtoReflect.Descriptor instead.
func (*ResolveMutationCreateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *ResolveMutationCreateUserResponse) GetData() *UserSource {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResolveMutationUpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,23236,opt,name=id,proto3" json:"id,omitempty"`
	Input         *UpdateUserInputSource `protobuf:"bytes,23683,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveMutationUpdateUserRequest) Reset() {
	*x = ResolveMutationUpdateUserRequest{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMutationUpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMutationUpdateUserRequest) ProtoMessage() {}

func (x *ResolveMutationUpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMutationUpdateUserRequest.ProtoReflect.Descriptor instead.
func (*ResolveMutationUpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *ResolveMutationUpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResolveMutationUpdateUserRequest) GetInput() *UpdateUserInputSource {
	if x != nil {
		return x.Input
	}
	return nil
}

type ResolveMutationUpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *UserSource            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveMutationUpdateUserResponse) Reset() {
	*x = ResolveMutationUpdateUserResponse{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMutationUpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMutationUpdateUserResponse) ProtoMessage() {}

func (x *ResolveMutationUpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMutationUpdateUserResponse.ProtoReflect.Descriptor instead.
func (*ResolveMutationUpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *ResolveMutationUpdateUserResponse) GetData() *UserSource {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResolveMutationDeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,23236,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveMutationDeleteUserRequest) Reset() {
	*x = ResolveMutationDeleteUserRequest{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMutationDeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMutationDeleteUserRequest) ProtoMessage() {}

func (x *ResolveMutationDeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMutationDeleteUserRequest.ProtoReflect.Descriptor instead.
func (*ResolveMutationDeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *ResolveMutationDeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResolveMutationDeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          bool                   `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveMutationDeleteUserResponse) Reset() {
	*x = ResolveMutationDeleteUserResponse{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMutationDeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMutationDeleteUserResponse) ProtoMessage() {}

func (x *ResolveMutationDeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMutationDeleteUserResponse.ProtoReflect.Descriptor instead.
func (*ResolveMutationDeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

func (x *ResolveMutationDeleteUserResponse) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

type ResolveUserPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,29641,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveUserPostsRequest) Reset() {
	*x = ResolveUserPostsRequest{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveUserPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveUserPostsRequest) ProtoMessage() {}

func (x *ResolveUserPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveUserPostsRequest.ProtoReflect.Descriptor instead.
func (*ResolveUserPostsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

func (x *ResolveUserPostsRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type ResolveUserPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*PostSource          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveUserPostsResponse) Reset() {
	*x = ResolveUserPostsResponse{}
	mi := &file_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveUserPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveUserPostsResponse) ProtoMessage() {}

func (x *ResolveUserPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveUserPostsResponse.ProtoReflect.Descriptor instead.
func (*ResolveUserPostsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{24}
}

func (x *ResolveUserPostsResponse) GetData() []*PostSource {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResolveOrganizationMemberCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,23236,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveOrganizationMemberCountRequest) Reset() {
	*x = ResolveOrganizationMemberCountRequest{}
	mi := &file_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveOrganizationMemberCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveOrganizationMemberCountRequest) ProtoMessage() {}

func (x *ResolveOrganizationMemberCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveOrganizationMemberCountRequest.ProtoReflect.Descriptor instead.
func (*ResolveOrganizationMemberCountRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{25}
}

func (x *ResolveOrganizationMemberCountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResolveOrganizationMemberCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          int32                  `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveOrganizationMemberCountResponse) Reset() {
	*x = ResolveOrganizationMemberCountResponse{}
	mi := &file_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveOrganizationMemberCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveOrganizationMemberCountResponse) ProtoMessage() {}

func (x *ResolveOrganizationMemberCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveOrganizationMemberCountResponse.ProtoReflect.Descriptor instead.
func (*ResolveOrganizationMemberCountResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{26}
}

func (x *ResolveOrganizationMemberCountResponse) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

type ResolveOrganizationMembersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,16616,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveOrganizationMembersRequest) Reset() {
	*x = ResolveOrganizationMembersRequest{}
	mi := &file_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveOrganizationMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveOrganizationMembersRequest) ProtoMessage() {}

func (x *ResolveOrganizationMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveOrganizationMembersRequest.ProtoReflect.Descriptor instead.
func (*ResolveOrganizationMembersRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{27}
}

func (x *ResolveOrganizationMembersRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type ResolveOrganizationMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*UserSource          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveOrganizationMembersResponse) Reset() {
	*x = ResolveOrganizationMembersResponse{}
	mi := &file_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveOrganizationMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveOrganizationMembersResponse) ProtoMessage() {}

func (x *ResolveOrganizationMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveOrganizationMembersResponse.ProtoReflect.Descriptor instead.
func (*ResolveOrganizationMembersResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{28}
}

func (x *ResolveOrganizationMembersResponse) GetData() []*UserSource {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResolvePostCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,23806,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvePostCommentsRequest) Reset() {
	*x = ResolvePostCommentsRequest{}
	mi := &file_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePostCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePostCommentsRequest) ProtoMessage() {}

func (x *ResolvePostCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePostCommentsRequest.ProtoReflect.Descriptor instead.
func (*ResolvePostCommentsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{29}
}

func (x *ResolvePostCommentsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type ResolvePostCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*CommentSource       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvePostCommentsResponse) Reset() {
	*x = ResolvePostCommentsResponse{}
	mi := &file_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePostCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePostCommentsResponse) ProtoMessage() {}

func (x *ResolvePostCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePostCommentsResponse.ProtoReflect.Descriptor instead.
func (*ResolvePostCommentsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{30}
}

func (x *ResolvePostCommentsResponse) GetData() []*CommentSource {
	if x != nil {
		return x.Data
	}
	return nil
}

type BatchLoadUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batches       []*LoadUserByIdRequest `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLoadUserByIdRequest) Reset() {
	*x = BatchLoadUserByIdRequest{}
	mi := &file_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLoadUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLoadUserByIdRequest) ProtoMessage() {}

func (x *BatchLoadUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLoadUserByIdRequest.ProtoReflect.Descriptor instead.
func (*BatchLoadUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{31}
}

func (x *BatchLoadUserByIdRequest) GetBatches() []*LoadUserByIdRequest {
	if x != nil {
		return x.Batches
	}
	return nil
}

type BatchLoadUserByIdResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Batches       []*LoadUserByIdResponse `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLoadUserByIdResponse) Reset() {
	*x = BatchLoadUserByIdResponse{}
	mi := &file_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLoadUserByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLoadUserByIdResponse) ProtoMessage() {}

func (x *BatchLoadUserByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLoadUserByIdResponse.ProtoReflect.Descriptor instead.
func (*BatchLoadUserByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{32}
}

func (x *BatchLoadUserByIdResponse) GetBatches() []*LoadUserByIdResponse {
	if x != nil {
		return x.Batches
	}
	return nil
}

type LoadUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,23236,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadUserByIdRequest) Reset() {
	*x = LoadUserByIdRequest{}
	mi := &file_user_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadUserByIdRequest) ProtoMessage() {}

func (x *LoadUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadUserByIdRequest.ProtoReflect.Descriptor instead.
func (*LoadUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{33}
}

func (x *LoadUserByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LoadUserByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *UserSource            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadUserByIdResponse) Reset() {
	*x = LoadUserByIdResponse{}
	mi := &file_user_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadUserByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadUserByIdResponse) ProtoMessage() {}

func (x *LoadUserByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadUserByIdResponse.ProtoReflect.Descriptor instead.
func (*LoadUserByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{34}
}

func (x *LoadUserByIdResponse) GetData() *UserSource {
	if x != nil {
		return x.Data
	}
	return nil
}

type BatchLoadUserByEmailRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Batches       []*LoadUserByEmailRequest `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLoadUserByEmailRequest) Reset() {
	*x = BatchLoadUserByEmailRequest{}
	mi := &file_user_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLoadUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLoadUserByEmailRequest) ProtoMessage() {}

func (x *BatchLoadUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLoadUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*BatchLoadUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{35}
}

func (x *BatchLoadUserByEmailRequest) GetBatches() []*LoadUserByEmailRequest {
	if x != nil {
		return x.Batches
	}
	return nil
}

type BatchLoadUserByEmailResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Batches       []*LoadUserByEmailResponse `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLoadUserByEmailResponse) Reset() {
	*x = BatchLoadUserByEmailResponse{}
	mi := &file_user_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLoadUserByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLoadUserByEmailResponse) ProtoMessage() {}

func (x *BatchLoadUserByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLoadUserByEmailResponse.ProtoReflect.Descriptor instead.
func (*BatchLoadUserByEmailResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{36}
}

func (x *BatchLoadUserByEmailResponse) GetBatches() []*LoadUserByEmailResponse {
	if x != nil {
		return x.Batches
	}
	return nil
}

type LoadUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,20000,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadUserByEmailRequest) Reset() {
	*x = LoadUserByEmailRequest{}
	mi := &file_user_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadUserByEmailRequest) ProtoMessage() {}

func (x *LoadUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*LoadUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{37}
}

func (x *LoadUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type LoadUserByEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *UserSource            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadUserByEmailResponse) Reset() {
	*x = LoadUserByEmailResponse{}
	mi := &file_user_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadUserByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadUserByEmailResponse) ProtoMessage() {}

func (x *LoadUserByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadUserByEmailResponse.ProtoReflect.Descriptor instead.
func (*LoadUserByEmailResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{38}
}

func (x *LoadUserByEmailResponse) GetData() *UserSource {
	if x != nil {
		return x.Data
	}
	return nil
}

type BatchLoadOrganizationByIdRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Batches       []*LoadOrganizationByIdRequest `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLoadOrganizationByIdRequest) Reset() {
	*x = BatchLoadOrganizationByIdRequest{}
	mi := &file_user_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLoadOrganizationByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLoadOrganizationByIdRequest) ProtoMessage() {}

func (x *BatchLoadOrganizationByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLoadOrganizationByIdRequest.ProtoReflect.Descriptor instead.
func (*BatchLoadOrganizationByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{39}
}

func (x *BatchLoadOrganizationByIdRequest) GetBatches() []*LoadOrganizationByIdRequest {
	if x != nil {
		return x.Batches
	}
	return nil
}

type BatchLoadOrganizationByIdResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Batches       []*LoadOrganizationByIdResponse `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLoadOrganizationByIdResponse) Reset() {
	*x = BatchLoadOrganizationByIdResponse{}
	mi := &file_user_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLoadOrganizationByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLoadOrganizationByIdResponse) ProtoMessage() {}

func (x *BatchLoadOrganizationByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLoadOrganizationByIdResponse.ProtoReflect.Descriptor instead.
func (*BatchLoadOrganizationByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{40}
}

func (x *BatchLoadOrganizationByIdResponse) GetBatches() []*LoadOrganizationByIdResponse {
	if x != nil {
		return x.Batches
	}
	return nil
}

type LoadOrganizationByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,23236,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadOrganizationByIdRequest) Reset() {
	*x = LoadOrganizationByIdRequest{}
	mi := &file_user_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadOrganizationByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadOrganizationByIdRequest) ProtoMessage() {}

func (x *LoadOrganizationByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadOrganizationByIdRequest.ProtoReflect.Descriptor instead.
func (*LoadOrganizationByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{41}
}

func (x *LoadOrganizationByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LoadOrganizationByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *OrganizationSource    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadOrganizationByIdResponse) Reset() {
	*x = LoadOrganizationByIdResponse{}
	mi := &file_user_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadOrganizationByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadOrganizationByIdResponse) ProtoMessage() {}

func (x *LoadOrganizationByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadOrganizationByIdResponse.ProtoReflect.Descriptor instead.
func (*LoadOrganizationByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{42}
}

func (x *LoadOrganizationByIdResponse) GetData() *OrganizationSource {
	if x != nil {
		return x.Data
	}
	return nil
}

type BatchLoadPostByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batches       []*LoadPostByIdRequest `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLoadPostByIdRequest) Reset() {
	*x = BatchLoadPostByIdRequest{}
	mi := &file_user_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLoadPostByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLoadPostByIdRequest) ProtoMessage() {}

func (x *BatchLoadPostByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLoadPostByIdRequest.ProtoReflect.Descriptor instead.
func (*BatchLoadPostByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{43}
}

func (x *BatchLoadPostByIdRequest) GetBatches() []*LoadPostByIdRequest {
	if x != nil {
		return x.Batches
	}
	return nil
}

type BatchLoadPostByIdResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Batches       []*LoadPostByIdResponse `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLoadPostByIdResponse) Reset() {
	*x = BatchLoadPostByIdResponse{}
	mi := &file_user_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLoadPostByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLoadPostByIdResponse) ProtoMessage() {}

func (x *BatchLoadPostByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLoadPostByIdResponse.ProtoReflect.Descriptor instead.
func (*BatchLoadPostByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{44}
}

func (x *BatchLoadPostByIdResponse) GetBatches() []*LoadPostByIdResponse {
	if x != nil {
		return x.Batches
	}
	return nil
}

type LoadPostByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,23236,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadPostByIdRequest) Reset() {
	*x = LoadPostByIdRequest{}
	mi := &file_user_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadPostByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPostByIdRequest) ProtoMessage() {}

func (x *LoadPostByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPostByIdRequest.ProtoReflect.Descriptor instead.
func (*LoadPostByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{45}
}

func (x *LoadPostByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LoadPostByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *PostSource            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadPostByIdResponse) Reset() {
	*x = LoadPostByIdResponse{}
	mi := &file_user_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadPostByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPostByIdResponse) ProtoMessage() {}

func (x *LoadPostByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPostByIdResponse.ProtoReflect.Descriptor instead.
func (*LoadPostByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{46}
}

func (x *LoadPostByIdResponse) GetData() *PostSource {
	if x != nil {
		return x.Data
	}
	return nil
}

type BatchLoadCommentByIdRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Batches       []*LoadCommentByIdRequest `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLoadCommentByIdRequest) Reset() {
	*x = BatchLoadCommentByIdRequest{}
	mi := &file_user_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLoadCommentByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLoadCommentByIdRequest) ProtoMessage() {}

func (x *BatchLoadCommentByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLoadCommentByIdRequest.ProtoReflect.Descriptor instead.
func (*BatchLoadCommentByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{47}
}

func (x *BatchLoadCommentByIdRequest) GetBatches() []*LoadCommentByIdRequest {
	if x != nil {
		return x.Batches
	}
	return nil
}

type BatchLoadCommentByIdResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Batches       []*LoadCommentByIdResponse `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLoadCommentByIdResponse) Reset() {
	*x = BatchLoadCommentByIdResponse{}
	mi := &file_user_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLoadCommentByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLoadCommentByIdResponse) ProtoMessage() {}

func (x *BatchLoadCommentByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLoadCommentByIdResponse.ProtoReflect.Descriptor instead.
func (*BatchLoadCommentByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{48}
}

func (x *BatchLoadCommentByIdResponse) GetBatches() []*LoadCommentByIdResponse {
	if x != nil {
		return x.Batches
	}
	return nil
}

type LoadCommentByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,23236,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadCommentByIdRequest) Reset() {
	*x = LoadCommentByIdRequest{}
	mi := &file_user_proto_msgTypes[49]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCommentByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCommentByIdRequest) ProtoMessage() {}

func (x *LoadCommentByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[49]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCommentByIdRequest.ProtoReflect.Descriptor instead.
func (*LoadCommentByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{49}
}

func (x *LoadCommentByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LoadCommentByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *CommentSource         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadCommentByIdResponse) Reset() {
	*x = LoadCommentByIdResponse{}
	mi := &file_user_proto_msgTypes[50]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCommentByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCommentByIdResponse) ProtoMessage() {}

func (x *LoadCommentByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[50]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCommentByIdResponse.ProtoReflect.Descriptor instead.
func (*LoadCommentByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{50}
}

func (x *LoadCommentByIdResponse) GetData() *CommentSource {
	if x != nil {
		return x.Data
	}
	return nil
}

type BatchLoadProfileByUserIdRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Batches       []*LoadProfileByUserIdRequest `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLoadProfileByUserIdRequest) Reset() {
	*x = BatchLoadProfileByUserIdRequest{}
	mi := &file_user_proto_msgTypes[51]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLoadProfileByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLoadProfileByUserIdRequest) ProtoMessage() {}

func (x *BatchLoadProfileByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[51]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLoadProfileByUserIdRequest.ProtoReflect.Descriptor instead.
func (*BatchLoadProfileByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{51}
}

func (x *BatchLoadProfileByUserIdRequest) GetBatches() []*LoadProfileByUserIdRequest {
	if x != nil {
		return x.Batches
	}
	return nil
}

type BatchLoadProfileByUserIdResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Batches       []*LoadProfileByUserIdResponse `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLoadProfileByUserIdResponse) Reset() {
	*x = BatchLoadProfileByUserIdResponse{}
	mi := &file_user_proto_msgTypes[52]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLoadProfileByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLoadProfileByUserIdResponse) ProtoMessage() {}

func (x *BatchLoadProfileByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[52]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLoadProfileByUserIdResponse.ProtoReflect.Descriptor instead.
func (*BatchLoadProfileByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{52}
}

func (x *BatchLoadProfileByUserIdResponse) GetBatches() []*LoadProfileByUserIdResponse {
	if x != nil {
		return x.Batches
	}
	return nil
}

type LoadProfileByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,12974,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadProfileByUserIdRequest) Reset() {
	*x = LoadProfileByUserIdRequest{}
	mi := &file_user_proto_msgTypes[53]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadProfileByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadProfileByUserIdRequest) ProtoMessage() {}

func (x *LoadProfileByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[53]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadProfileByUserIdRequest.ProtoReflect.Descriptor instead.
func (*LoadProfileByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{53}
}

func (x *LoadProfileByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LoadProfileByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ProfileSource         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadProfileByUserIdResponse) Reset() {
	*x = LoadProfileByUserIdResponse{}
	mi := &file_user_proto_msgTypes[54]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadProfileByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadProfileByUserIdResponse) ProtoMessage() {}

func (x *LoadProfileByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[54]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadProfileByUserIdResponse.ProtoReflect.Descriptor instead.
func (*LoadProfileByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{54}
}

func (x *LoadProfileByUserIdResponse) GetData() *ProfileSource {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x06simple\"B\n" +
	"\n" +
	"NodeSource\x12\x1a\n" +
	"\btypename\x18\x01 \x01(\tR\btypename\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\xb8\x01\n" +
	"\x12SearchResultSource\x12*\n" +
	"\x04Post\x18\x9b\xb9\x01 \x01(\v2\x12.simple.PostSourceH\x00R\x04Post\x12*\n" +
	"\x04User\x18\xa7\xd5\x01 \x01(\v2\x12.simple.UserSourceH\x00R\x04User\x12A\n" +
	"\fOrganization\x18\xb9G \x01(\v2\x1a.simple.OrganizationSourceH\x00R\fOrganizationB\a\n" +
	"\x05value\"\xeb\x01\n" +
	"\n" +
	"UserSource\x12\x10\n" +
	"\x02id\x18ĵ\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x05email\x18\xa0\x9c\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x04name\x18\xe8\xe9\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x03age\x18ɋ\x01 \x01(\x05R\x03age\x12\x1d\n" +
	"\tis_active\x18\xe1\x82\x01 \x01(\bR\bisActive\x12\x1e\n" +
	"\n" +
	"created_at\x18\xaa9 \x01(\tR\tcreatedAt\x12\x1f\n" +
	"\n" +
	"updated_at\x18\x90\x8e\x01 \x01(\tR\tupdatedAt\x12)\n" +
	"\x0forganization_id\x18\xe8\x81\x01 \x01(\tR\x0eorganizationId\"_\n" +
	"\x12OrganizationSource\x12\x10\n" +
	"\x02id\x18ĵ\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x04name\x18\xe8\xe9\x01 \x01(\tR\x04name\x12!\n" +
	"\vdescription\x18\xf6f \x01(\tR\vdescription\"\x90\x01\n" +
	"\n" +
	"PostSource\x12\x10\n" +
	"\x02id\x18ĵ\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x05title\x18\xe0\x1b \x01(\tR\x05title\x12\x1a\n" +
	"\acontent\x18\xbf\xbf\x01 \x01(\tR\acontent\x12\x1e\n" +
	"\tpublished\x18\xa8\xb3\x01 \x01(\bR\tpublished\x12\x1d\n" +
	"\tauthor_id\x18\xc9\xe7\x01 \x01(\tR\bauthorId\"w\n" +
	"\rCommentSource\x12\x10\n" +
	"\x02id\x18ĵ\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\acontent\x18\xbf\xbf\x01 \x01(\tR\acontent\x12\x19\n" +
	"\apost_id\x18\xfe\xb9\x01 \x01(\tR\x06postId\x12\x1d\n" +
	"\tauthor_id\x18\xc9\xe7\x01 \x01(\tR\bauthorId\"p\n" +
	"\rProfileSource\x12\x10\n" +
	"\x02id\x18ĵ\x01 \x01(\tR\x02id\x12\x18\n" +
	"\auser_id\x18\xaee \x01(\tR\x06userId\x12\x12\n" +
	"\x03bio\x18\xe0\x9d\x01 \x01(\tR\x03bio\x12\x1f\n" +
	"\n" +
	"avatar_url\x18\x87\xa3\x01 \x01(\tR\tavatarUrl\"\x84\x01\n" +
	"\x15CreateUserInputSource\x12\x16\n" +
	"\x05email\x18\xa0\x9c\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x04name\x18\xe8\xe9\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x03age\x18ɋ\x01 \x01(\x05R\x03age\x12)\n" +
	"\x0forganization_id\x18\xe8\x81\x01 \x01(\tR\x0eorganizationId\"x\n" +
	"\x15UpdateUserInputSource\x12\x16\n" +
	"\x05email\x18\xa0\x9c\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x04name\x18\xe8\xe9\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x03age\x18ɋ\x01 \x01(\x05R\x03age\x12\x1d\n" +
	"\tis_active\x18\xe1\x82\x01 \x01(\bR\bisActive\"+\n" +
	"\x17ResolveQueryUserRequest\x12\x10\n" +
	"\x02id\x18ĵ\x01 \x01(\tR\x02id\"B\n" +
	"\x18ResolveQueryUserResponse\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.simple.UserSourceR\x04data\"\x1a\n" +
	"\x18ResolveQueryUsersRequest\"C\n" +
	"\x19ResolveQueryUsersResponse\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.simple.UserSourceR\x04data\"+\n" +
	"\x17ResolveQueryNodeRequest\x12\x10\n" +
	"\x02id\x18ĵ\x01 \x01(\tR\x02id\"B\n" +
	"\x18ResolveQueryNodeResponse\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.simple.NodeSourceR\x04data\"1\n" +
	"\x19ResolveQuerySearchRequest\x12\x14\n" +
	"\x04term\x18\xe6\xd3\x01 \x01(\tR\x04term\"L\n" +
	"\x1aResolveQuerySearchResponse\x12.\n" +
	"\x04data\x18\x01 \x03(\v2\x1a.simple.SearchResultSourceR\x04data\"Y\n" +
	" ResolveMutationCreateUserRequest\x125\n" +
	"\x05input\x18\x83\xb9\x01 \x01(\v2\x1d.simple.CreateUserInputSourceR\x05input\"K\n" +
	"!ResolveMutationCreateUserResponse\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.simple.UserSourceR\x04data\"k\n" +
	" ResolveMutationUpdateUserRequest\x12\x10\n" +
	"\x02id\x18ĵ\x01 \x01(\tR\x02id\x125\n" +
	"\x05input\x18\x83\xb9\x01 \x01(\v2\x1d.simple.UpdateUserInputSourceR\x05input\"K\n" +
	"!ResolveMutationUpdateUserResponse\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.simple.UserSourceR\x04data\"4\n" +
	" ResolveMutationDeleteUserRequest\x12\x10\n" +
	"\x02id\x18ĵ\x01 \x01(\tR\x02id\"7\n" +
	"!ResolveMutationDeleteUserResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\bR\x04data\"8\n" +
	"\x17ResolveUserPostsRequest\x12\x1d\n" +
	"\tauthor_id\x18\xc9\xe7\x01 \x01(\tR\bauthorId\"B\n" +
	"\x18ResolveUserPostsResponse\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.simple.PostSourceR\x04data\"9\n" +
	"%ResolveOrganizationMemberCountRequest\x12\x10\n" +
	"\x02id\x18ĵ\x01 \x01(\tR\x02id\"<\n" +
	"&ResolveOrganizationMemberCountResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\x05R\x04data\"N\n" +
	"!ResolveOrganizationMembersRequest\x12)\n" +
	"\x0forganization_id\x18\xe8\x81\x01 \x01(\tR\x0eorganizationId\"L\n" +
	"\"ResolveOrganizationMembersResponse\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.simple.UserSourceR\x04data\"7\n" +
	"\x1aResolvePostCommentsRequest\x12\x19\n" +
	"\apost_id\x18\xfe\xb9\x01 \x01(\tR\x06postId\"H\n" +
	"\x1bResolvePostCommentsResponse\x12)\n" +
	"\x04data\x18\x01 \x03(\v2\x15.simple.CommentSourceR\x04data\"Q\n" +
	"\x18BatchLoadUserByIdRequest\x125\n" +
	"\abatches\x18\x01 \x03(\v2\x1b.simple.LoadUserByIdRequestR\abatches\"S\n" +
	"\x19BatchLoadUserByIdResponse\x126\n" +
	"\abatches\x18\x01 \x03(\v2\x1c.simple.LoadUserByIdResponseR\abatches\"'\n" +
	"\x13LoadUserByIdRequest\x12\x10\n" +
	"\x02id\x18ĵ\x01 \x01(\tR\x02id\">\n" +
	"\x14LoadUserByIdResponse\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.simple.UserSourceR\x04data\"W\n" +
	"\x1bBatchLoadUserByEmailRequest\x128\n" +
	"\abatches\x18\x01 \x03(\v2\x1e.simple.LoadUserByEmailRequestR\abatches\"Y\n" +
	"\x1cBatchLoadUserByEmailResponse\x129\n" +
	"\abatches\x18\x01 \x03(\v2\x1f.simple.LoadUserByEmailResponseR\abatches\"0\n" +
	"\x16LoadUserByEmailRequest\x12\x16\n" +
	"\x05email\x18\xa0\x9c\x01 \x01(\tR\x05email\"A\n" +
	"\x17LoadUserByEmailResponse\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.simple.UserSourceR\x04data\"a\n" +
	" BatchLoadOrganizationByIdRequest\x12=\n" +
	"\abatches\x18\x01 \x03(\v2#.simple.LoadOrganizationByIdRequestR\abatches\"c\n" +
	"!BatchLoadOrganizationByIdResponse\x12>\n" +
	"\abatches\x18\x01 \x03(\v2$.simple.LoadOrganizationByIdResponseR\abatches\"/\n" +
	"\x1bLoadOrganizationByIdRequest\x12\x10\n" +
	"\x02id\x18ĵ\x01 \x01(\tR\x02id\"N\n" +
	"\x1cLoadOrganizationByIdResponse\x12.\n" +
	"\x04data\x18\x01 \x01(\v2\x1a.simple.OrganizationSourceR\x04data\"Q\n" +
	"\x18BatchLoadPostByIdRequest\x125\n" +
	"\abatches\x18\x01 \x03(\v2\x1b.simple.LoadPostByIdRequestR\abatches\"S\n" +
	"\x19BatchLoadPostByIdResponse\x126\n" +
	"\abatches\x18\x01 \x03(\v2\x1c.simple.LoadPostByIdResponseR\abatches\"'\n" +
	"\x13LoadPostByIdRequest\x12\x10\n" +
	"\x02id\x18ĵ\x01 \x01(\tR\x02id\">\n" +
	"\x14LoadPostByIdResponse\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.simple.PostSourceR\x04data\"W\n" +
	"\x1bBatchLoadCommentByIdRequest\x128\n" +
	"\abatches\x18\x01 \x03(\v2\x1e.simple.LoadCommentByIdRequestR\abatches\"Y\n" +
	"\x1cBatchLoadCommentByIdResponse\x129\n" +
	"\abatches\x18\x01 \x03(\v2\x1f.simple.LoadCommentByIdResponseR\abatches\"*\n" +
	"\x16LoadCommentByIdRequest\x12\x10\n" +
	"\x02id\x18ĵ\x01 \x01(\tR\x02id\"D\n" +
	"\x17LoadCommentByIdResponse\x12)\n" +
	"\x04data\x18\x01 \x01(\v2\x15.simple.CommentSourceR\x04data\"_\n" +
	"\x1fBatchLoadProfileByUserIdRequest\x12<\n" +
	"\abatches\x18\x01 \x03(\v2\".simple.LoadProfileByUserIdRequestR\abatches\"a\n" +
	" BatchLoadProfileByUserIdResponse\x12=\n" +
	"\abatches\x18\x01 \x03(\v2#.simple.LoadProfileByUserIdResponseR\abatches\"6\n" +
	"\x1aLoadProfileByUserIdRequest\x12\x18\n" +
	"\auser_id\x18\xaee \x01(\tR\x06userId\"H\n" +
	"\x1bLoadProfileByUserIdResponse\x12)\n" +
	"\x04data\x18\x01 \x01(\v2\x15.simple.ProfileSourceR\x04data2\xd0\r\n" +
	"\vUserService\x12U\n" +
	"\x10ResolveQueryUser\x12\x1f.simple.ResolveQueryUserRequest\x1a .simple.ResolveQueryUserResponse\x12X\n" +
	"\x11ResolveQueryUsers\x12 .simple.ResolveQueryUsersRequest\x1a!.simple.ResolveQueryUsersResponse\x12U\n" +
	"\x10ResolveQueryNode\x12\x1f.simple.ResolveQueryNodeRequest\x1a .simple.ResolveQueryNodeResponse\x12[\n" +
	"\x12ResolveQuerySearch\x12!.simple.ResolveQuerySearchRequest\x1a\".simple.ResolveQuerySearchResponse\x12p\n" +
	"\x19ResolveMutationCreateUser\x12(.simple.ResolveMutationCreateUserRequest\x1a).simple.ResolveMutationCreateUserResponse\x12p\n" +
	"\x19ResolveMutationUpdateUser\x12(.simple.ResolveMutationUpdateUserRequest\x1a).simple.ResolveMutationUpdateUserResponse\x12p\n" +
	"\x19ResolveMutationDeleteUser\x12(.simple.ResolveMutationDeleteUserRequest\x1a).simple.ResolveMutationDeleteUserResponse\x12U\n" +
	"\x10ResolveUserPosts\x12\x1f.simple.ResolveUserPostsRequest\x1a .simple.ResolveUserPostsResponse\x12\x7f\n" +
	"\x1eResolveOrganizationMemberCount\x12-.simple.ResolveOrganizationMemberCountRequest\x1a..simple.ResolveOrganizationMemberCountResponse\x12s\n" +
	"\x1aResolveOrganizationMembers\x12).simple.ResolveOrganizationMembersRequest\x1a*.simple.ResolveOrganizationMembersResponse\x12^\n" +
	"\x13ResolvePostComments\x12\".simple.ResolvePostCommentsRequest\x1a#.simple.ResolvePostCommentsResponse\x12X\n" +
	"\x11BatchLoadUserById\x12 .simple.BatchLoadUserByIdRequest\x1a!.simple.BatchLoadUserByIdResponse\x12a\n" +
	"\x14BatchLoadUserByEmail\x12#.simple.BatchLoadUserByEmailRequest\x1a$.simple.BatchLoadUserByEmailResponse\x12p\n" +
	"\x19BatchLoadOrganizationById\x12(.simple.BatchLoadOrganizationByIdRequest\x1a).simple.BatchLoadOrganizationByIdResponse\x12X\n" +
	"\x11BatchLoadPostById\x12 .simple.BatchLoadPostByIdRequest\x1a!.simple.BatchLoadPostByIdResponse\x12a\n" +
	"\x14BatchLoadCommentById\x12#.simple.BatchLoadCommentByIdRequest\x1a$.simple.BatchLoadCommentByIdResponse\x12m\n" +
	"\x18BatchLoadProfileByUserId\x12'.simple.BatchLoadProfileByUserIdRequest\x1a(.simple.BatchLoadProfileByUserIdResponseb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 55)
var file_user_proto_goTypes = []any{
	(*NodeSource)(nil),                             // 0: simple.NodeSource
	(*SearchResultSource)(nil),                     // 1: simple.SearchResultSource
	(*UserSource)(nil),                             // 2: simple.UserSource
	(*OrganizationSource)(nil),                     // 3: simple.OrganizationSource
	(*PostSource)(nil),                             // 4: simple.PostSource
	(*CommentSource)(nil),                          // 5: simple.CommentSource
	(*ProfileSource)(nil),                          // 6: simple.ProfileSource
	(*CreateUserInputSource)(nil),                  // 7: simple.CreateUserInputSource
	(*UpdateUserInputSource)(nil),                  // 8: simple.UpdateUserInputSource
	(*ResolveQueryUserRequest)(nil),                // 9: simple.ResolveQueryUserRequest
	(*ResolveQueryUserResponse)(nil),               // 10: simple.ResolveQueryUserResponse
	(*ResolveQueryUsersRequest)(nil),               // 11: simple.ResolveQueryUsersRequest
	(*ResolveQueryUsersResponse)(nil),              // 12: simple.ResolveQueryUsersResponse
	(*ResolveQueryNodeRequest)(nil),                // 13: simple.ResolveQueryNodeRequest
	(*ResolveQueryNodeResponse)(nil),               // 14: simple.ResolveQueryNodeResponse
	(*ResolveQuerySearchRequest)(nil),              // 15: simple.ResolveQuerySearchRequest
	(*ResolveQuerySearchResponse)(nil),             // 16: simple.ResolveQuerySearchResponse
	(*ResolveMutationCreateUserRequest)(nil),       // 17: simple.ResolveMutationCreateUserRequest
	(*ResolveMutationCreateUserResponse)(nil),      // 18: simple.ResolveMutationCreateUserResponse
	(*ResolveMutationUpdateUserRequest)(nil),       // 19: simple.ResolveMutationUpdateUserRequest
	(*ResolveMutationUpdateUserResponse)(nil),      // 20: simple.ResolveMutationUpdateUserResponse
	(*ResolveMutationDeleteUserRequest)(nil),       // 21: simple.ResolveMutationDeleteUserRequest
	(*ResolveMutationDeleteUserResponse)(nil),      // 22: simple.ResolveMutationDeleteUserResponse
	(*ResolveUserPostsRequest)(nil),                // 23: simple.ResolveUserPostsRequest
	(*ResolveUserPostsResponse)(nil),               // 24: simple.ResolveUserPostsResponse
	(*ResolveOrganizationMemberCountRequest)(nil),  // 25: simple.ResolveOrganizationMemberCountRequest
	(*ResolveOrganizationMemberCountResponse)(nil), // 26: simple.ResolveOrganizationMemberCountResponse
	(*ResolveOrganizationMembersRequest)(nil),      // 27: simple.ResolveOrganizationMembersRequest
	(*ResolveOrganizationMembersResponse)(nil),     // 28: simple.ResolveOrganizationMembersResponse
	(*ResolvePostCommentsRequest)(nil),             // 29: simple.ResolvePostCommentsRequest
	(*ResolvePostCommentsResponse)(nil),            // 30: simple.ResolvePostCommentsResponse
	(*BatchLoadUserByIdRequest)(nil),               // 31: simple.BatchLoadUserByIdRequest
	(*BatchLoadUserByIdResponse)(nil),              // 32: simple.BatchLoadUserByIdResponse
	(*LoadUserByIdRequest)(nil),                    // 33: simple.LoadUserByIdRequest
	(*LoadUserByIdResponse)(nil),                   // 34: simple.LoadUserByIdResponse
	(*BatchLoadUserByEmailRequest)(nil),            // 35: simple.BatchLoadUserByEmailRequest
	(*BatchLoadUserByEmailResponse)(nil),           // 36: simple.BatchLoadUserByEmailResponse
	(*LoadUserByEmailRequest)(nil),                 // 37: simple.LoadUserByEmailRequest
	(*LoadUserByEmailResponse)(nil),                // 38: simple.LoadUserByEmailResponse
	(*BatchLoadOrganizationByIdRequest)(nil),       // 39: simple.BatchLoadOrganizationByIdRequest
	(*BatchLoadOrganizationByIdResponse)(nil),      // 40: simple.BatchLoadOrganizationByIdResponse
	(*LoadOrganizationByIdRequest)(nil),            // 41: simple.LoadOrganizationByIdRequest
	(*LoadOrganizationByIdResponse)(nil),           // 42: simple.LoadOrganizationByIdResponse
	(*BatchLoadPostByIdRequest)(nil),               // 43: simple.BatchLoadPostByIdRequest
	(*BatchLoadPostByIdResponse)(nil),              // 44: simple.BatchLoadPostByIdResponse
	(*LoadPostByIdRequest)(nil),                    // 45: simple.LoadPostByIdRequest
	(*LoadPostByIdResponse)(nil),                   // 46: simple.LoadPostByIdResponse
	(*BatchLoadCommentByIdRequest)(nil),            // 47: simple.BatchLoadCommentByIdRequest
	(*BatchLoadCommentByIdResponse)(nil),           // 48: simple.BatchLoadCommentByIdResponse
	(*LoadCommentByIdRequest)(nil),                 // 49: simple.LoadCommentByIdRequest
	(*LoadCommentByIdResponse)(nil),                // 50: simple.LoadCommentByIdResponse
	(*BatchLoadProfileByUserIdRequest)(nil),        // 51: simple.BatchLoadProfileByUserIdRequest
	(*BatchLoadProfileByUserIdResponse)(nil),       // 52: simple.BatchLoadProfileByUserIdResponse
	(*LoadProfileByUserIdRequest)(nil),             // 53: simple.LoadProfileByUserIdRequest
	(*LoadProfileByUserIdResponse)(nil),            // 54: simple.LoadProfileByUserIdResponse
}
var file_user_proto_depIdxs = []int32{
	4,  // 0: simple.SearchResultSource.Post:type_name -> simple.PostSource
	2,  // 1: simple.SearchResultSource.User:type_name -> simple.UserSource
	3,  // 2: simple.SearchResultSource.Organization:type_name -> simple.OrganizationSource
	2,  // 3: simple.ResolveQueryUserResponse.data:type_name -> simple.UserSource
	2,  // 4: simple.ResolveQueryUsersResponse.data:type_name -> simple.UserSource
	0,  // 5: simple.ResolveQueryNodeResponse.data:type_name -> simple.NodeSource
	1,  // 6: simple.ResolveQuerySearchResponse.data:type_name -> simple.SearchResultSource
	7,  // 7: simple.ResolveMutationCreateUserRequest.input:type_name -> simple.CreateUserInputSource
	2,  // 8: simple.ResolveMutationCreateUserResponse.data:type_name -> simple.UserSource
	8,  // 9: simple.ResolveMutationUpdateUserRequest.input:type_name -> simple.UpdateUserInputSource
	2,  // 10: simple.ResolveMutationUpdateUserResponse.data:type_name -> simple.UserSource
	4,  // 11: simple.ResolveUserPostsResponse.data:type_name -> simple.PostSource
	2,  // 12: simple.ResolveOrganizationMembersResponse.data:type_name -> simple.UserSource
	5,  // 13: simple.ResolvePostCommentsResponse.data:type_name -> simple.CommentSource
	33, // 14: simple.BatchLoadUserByIdRequest.batches:type_name -> simple.LoadUserByIdRequest
	34, // 15: simple.BatchLoadUserByIdResponse.batches:type_name -> simple.LoadUserByIdResponse
	2,  // 16: simple.LoadUserByIdResponse.data:type_name -> simple.UserSource
	37, // 17: simple.BatchLoadUserByEmailRequest.batches:type_name -> simple.LoadUserByEmailRequest
	38, // 18: simple.BatchLoadUserByEmailResponse.batches:type_name -> simple.LoadUserByEmailResponse
	2,  // 19: simple.LoadUserByEmailResponse.data:type_name -> simple.UserSource
	41, // 20: simple.BatchLoadOrganizationByIdRequest.batches:type_name -> simple.LoadOrganizationByIdRequest
	42, // 21: simple.BatchLoadOrganizationByIdResponse.batches:type_name -> simple.LoadOrganizationByIdResponse
	3,  // 22: simple.LoadOrganizationByIdResponse.data:type_name -> simple.OrganizationSource
	45, // 23: simple.BatchLoadPostByIdRequest.batches:type_name -> simple.LoadPostByIdRequest
	46, // 24: simple.BatchLoadPostByIdResponse.batches:type_name -> simple.LoadPostByIdResponse
	4,  // 25: simple.LoadPostByIdResponse.data:type_name -> simple.PostSource
	49, // 26: simple.BatchLoadCommentByIdRequest.batches:type_name -> simple.LoadCommentByIdRequest
	50, // 27: simple.BatchLoadCommentByIdResponse.batches:type_name -> simple.LoadCommentByIdResponse
	5,  // 28: simple.LoadCommentByIdResponse.data:type_name -> simple.CommentSource
	53, // 29: simple.BatchLoadProfileByUserIdRequest.batches:type_name -> simple.LoadProfileByUserIdRequest
	54, // 30: simple.BatchLoadProfileByUserIdResponse.batches:type_name -> simple.LoadProfileByUserIdResponse
	6,  // 31: simple.LoadProfileByUserIdResponse.data:type_name -> simple.ProfileSource
	9,  // 32: simple.UserService.ResolveQueryUser:input_type -> simple.ResolveQueryUserRequest
	11, // 33: simple.UserService.ResolveQueryUsers:input_type -> simple.ResolveQueryUsersRequest
	13, // 34: simple.UserService.ResolveQueryNode:input_type -> simple.ResolveQueryNodeRequest
	15, // 35: simple.UserService.ResolveQuerySearch:input_type -> simple.ResolveQuerySearchRequest
	17, // 36: simple.UserService.ResolveMutationCreateUser:input_type -> simple.ResolveMutationCreateUserRequest
	19, // 37: simple.UserService.ResolveMutationUpdateUser:input_type -> simple.ResolveMutationUpdateUserRequest
	21, // 38: simple.UserService.ResolveMutationDeleteUser:input_type -> simple.ResolveMutationDeleteUserRequest
	23, // 39: simple.UserService.ResolveUserPosts:input_type -> simple.ResolveUserPostsRequest
	25, // 40: simple.UserService.ResolveOrganizationMemberCount:input_type -> simple.ResolveOrganizationMemberCountRequest
	27, // 41: simple.UserService.ResolveOrganizationMembers:input_type -> simple.ResolveOrganizationMembersRequest
	29, // 42: simple.UserService.ResolvePostComments:input_type -> simple.ResolvePostCommentsRequest
	31, // 43: simple.UserService.BatchLoadUserById:input_type -> simple.BatchLoadUserByIdRequest
	35, // 44: simple.UserService.BatchLoadUserByEmail:input_type -> simple.BatchLoadUserByEmailRequest
	39, // 45: simple.UserService.BatchLoadOrganizationById:input_type -> simple.BatchLoadOrganizationByIdRequest
	43, // 46: simple.UserService.BatchLoadPostById:input_type -> simple.BatchLoadPostByIdRequest
	47, // 47: simple.UserService.BatchLoadCommentById:input_type -> simple.BatchLoadCommentByIdRequest
	51, // 48: simple.UserService.BatchLoadProfileByUserId:input_type -> simple.BatchLoadProfileByUserIdRequest
	10, // 49: simple.UserService.ResolveQueryUser:output_type -> simple.ResolveQueryUserResponse
	12, // 50: simple.UserService.ResolveQueryUsers:output_type -> simple.ResolveQueryUsersResponse
	14, // 51: simple.UserService.ResolveQueryNode:output_type -> simple.ResolveQueryNodeResponse
	16, // 52: simple.UserService.ResolveQuerySearch:output_type -> simple.ResolveQuerySearchResponse
	18, // 53: simple.UserService.ResolveMutationCreateUser:output_type -> simple.ResolveMutationCreateUserResponse
	20, // 54: simple.UserService.ResolveMutationUpdateUser:output_type -> simple.ResolveMutationUpdateUserResponse
	22, // 55: simple.UserService.ResolveMutationDeleteUser:output_type -> simple.ResolveMutationDeleteUserResponse
	24, // 56: simple.UserService.ResolveUserPosts:output_type -> simple.ResolveUserPostsResponse
	26, // 57: simple.UserService.ResolveOrganizationMemberCount:output_type -> simple.ResolveOrganizationMemberCountResponse
	28, // 58: simple.UserService.ResolveOrganizationMembers:output_type -> simple.ResolveOrganizationMembersResponse
	30, // 59: simple.UserService.ResolvePostComments:output_type -> simple.ResolvePostCommentsResponse
	32, // 60: simple.UserService.BatchLoadUserById:output_type -> simple.BatchLoadUserByIdResponse
	36, // 61: simple.UserService.BatchLoadUserByEmail:output_type -> simple.BatchLoadUserByEmailResponse
	40, // 62: simple.UserService.BatchLoadOrganizationById:output_type -> simple.BatchLoadOrganizationByIdResponse
	44, // 63: simple.UserService.BatchLoadPostById:output_type -> simple.BatchLoadPostByIdResponse
	48, // 64: simple.UserService.BatchLoadCommentById:output_type -> simple.BatchLoadCommentByIdResponse
	52, // 65: simple.UserService.BatchLoadProfileByUserId:output_type -> simple.BatchLoadProfileByUserIdResponse
	49, // [49:66] is the sub-list for method output_type
	32, // [32:49] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[1].OneofWrappers = []any{
		(*SearchResultSource_Post)(nil),
		(*SearchResultSource_User)(nil),
		(*SearchResultSource_Organization)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   55,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
